---
deployment:
  tasks:
    - export DEPLOYPATH=/home/zbkqwkdw8tdn/public_html
    - /bin/rm $DEPLOYPATH/en/index.html.old
    - /bin/rm $DEPLOYPATH/es/index.html.old
    - /bin/rm $DEPLOYPATH/css/styles.css.old
    - /bin/rm -R $DEPLOYPATH/assets.old
    - /bin/mv $DEPLOYPATH/en/index.html $DEPLOYPATH/en/index.html.old
    - /bin/mv $DEPLOYPATH/es/index.html $DEPLOYPATH/es/index.html.old
    - /bin/mv $DEPLOYPATH/css/styles.css $DEPLOYPATH/css/styles.css.old
    - /bin/mv -R $DEPLOYPATH/assets $DEPLOYPATH/assets.old
    - /bin/cp ./en/index.html $DEPLOYPATH/en/
    - /bin/cp ./es/index.html $DEPLOYPATH/es/
    - /bin/cp ./css/styles.css $DEPLOYPATH/css/
    - /bin/cp -R ./assets $DEPLOYPATH/